version: "3.8"

services:
  stylegan3: &stylegan3
    build:
      context: .
      dockerfile: ./src/stylegan3/Dockerfile
    hostname: stylegan3
    container_name: stylegan3
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu, compute, graphics]
    shm_size: '2gb'
    volumes:
      - .:/workspace
    environment:
      CACHE_DIR: "/local"
      PYTHONPATH: "/workspace" # needed so that Python finds the built Python 'sky_image_generator' module
      DNNLIB_CACHE_DIR: "/local"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
