name: stylegan3
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python==3.9
  - pip
  - numpy
  - click
  - pillow
  - scipy
  - pytorch=1.9.1
  - cudatoolkit
  - requests
  - tqdm
  - ninja
  - matplotlib
  - imageio
  - opencv
  - pandas
  - diskcache
  - pybind11
  - pip:
    - imgui
    - glfw
    - pyopengl
    - imageio-ffmpeg
    - pyspng
    - psutil
