version: "3.8"

services:
  stylegan3:
    build: .
    hostname: stylegan3
    container_name: stylegan3
    privileged: true
    stdin_open: true
    tty: true
    shm_size: '8gb'
    volumes:
      - ..:/workspace
      - ../datasets/skymangler:/workspace/datasets/skymangler
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1', '2']
              capabilities: [gpu]
    environment:
      CACHE_DIR: "/local"
      PYTHONPATH: "/workspace" # needed so that Python finds the built Python 'sky_image_generator' module
      DNNLIB_CACHE_DIR: "/local"
